matches:
  - trigger: ":utcdate"
    replace: "{{utc_date}}"
    vars:
      - name: utc_date
        type: shell
        params:
          cmd: "date -u +\"%Y-%m-%dT%TZ\""

  - trigger: ":publicip"
    replace: "{{public_ip}}"
    vars:
      - name: public_ip
        type: shell
        params:
          cmd: "dig +short myip.opendns.com @resolver1.opendns.com"

  - trigger: ":localip"
    replace: "{{local_ip}}"
    vars: 
      - name: local_ip
        type: shell
        params:
          cmd: "ipconfig getifaddr en0"

  - trigger: ":ngrokurl"
    replace: "{{output}}"
    label: "Get the ngrok url (ngrok needs to be running beforehand)"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl --silent --show-error http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'"
  
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"

  # Dummy Credit Cards for Testing
  - trigger: ":ccvisa"
    replace: "4012888888881881"

  - trigger: ":ccmc"
    replace: "5105105105105100"

  - trigger: ":ccamex"
    replace: "378282246310005"

  - trigger: ":ccdisco"
    replace: "6011111111111117"

  - trigger: ":cbempty"
    replace: "◻️"

  - trigger: ":cbchecked"
    replace: "✅"

  - trigger: ":checkmark"
    replace: "✓"